version: "2.1"

services:
  whoami:
    image: jwilder/whoami:latest
    restart: always
    networks:
      - web
      - default
    expose:
      - "8000"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:app.my-awesome-app.org"
      - "traefik.port=9000"
      - "traefik.basic.protocol=http"

networks:
  web:
    external: true
